'use strict'

const User = require('../models/user')

module.exports.getUser = (req, res, err) => {
	// UserId generated by session
	let userId = req.session.uid
	console.log("userId", userId);
	User
		.findById(userId)
		.then((user) => {
			console.log("Got user", user);
			res.json(user)
		})
		.catch(err)
}


// module.exports.getUserTeamFunc = (req, res) => {

// } 

// module.exports.getTDOFunc = (req, res) => {

// } 

// module.exports.getReminderFunc = (req, res) => {

// } 