'use strict'

const User = require('../models/user')
const mongoose = require('mongoose')
const { get } = require('request')
// Heroku deployment interferes with use of dotenv
const dotenv = require('dotenv')
// This now happens through Heroku
const { MYSPORTSFEEDSSCHEDULE_URL } = process.env

module.exports.getUser = (req, res, err) => {
	// UserId generated by session
	let userId = req.session.uid
	console.log("userId", userId);
	User
		.findById(userId)
		.then((user) => {
			console.log("Got user", user);
			res.json(user)
		})
		.catch(err)
} 


// module.exports.getSpecificName = (req, res) => {
// 	let teamId = req.params.teamId
// 		get(MYSPORTSFEEDSSCHEDULE_URL, (err, response, body) => {

// 		let allScheduleInfo = JSON.parse(body),
// 		{ fullgameschedule } = allScheduleInfo,
// 		{ lastUpdatedOn, gameentry } = fullgameschedule, // gameentry.length = 256
// 		games = gameentry

// 		getTeamSeason(games, 56)

// 		// let teamSeason = getTeamSeason(games, teamId)
// 		// res.json(teamSeason)
// 	})
// }



// module.exports.getReminderFunc = (req, res) => {

// } 